solution of 17

#include <iostream>
#include <vector>
using namespace std;

vector<int> increment(int N, vector<int>& arr) {
    for (int i = N - 1; i >= 0; i--) {
        if (arr[i] < 9) {
            arr[i]++;
            return arr;
        }
       
        arr[i] = 0;
    }
    arr.insert(arr.begin(), 1);
    return arr;
}
